/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package computerstore;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.PreparedStatement;

import java.sql.Connection;
 // Assuming you need DBCon class (adjust if needed)
import computerstore.dbcon;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sadir
 */
public class begin extends javax.swing.JFrame {

    /**
     * Creates new form begin
     */
     private final Connection con;
   
     private final dbcon dbConnector;
    public begin() {
        initComponents();
         
        dbConnector = new dbcon(); // Instantiate dbcon in the constructor
        con = dbConnector.connect(); // Initialize con using dbConnector

        if (con != null) {
            System.out.println("Database connection successful.");
        } else {
            System.out.println("Failed to connect to the database.");
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        category_btn = new javax.swing.JButton();
        customer_btn = new javax.swing.JButton();
        discount_btn = new javax.swing.JButton();
        inventory_btn = new javax.swing.JButton();
        payment_btn = new javax.swing.JButton();
        products_btn = new javax.swing.JButton();
        repairs_btn = new javax.swing.JButton();
        services_btn = new javax.swing.JButton();
        shipping_btn = new javax.swing.JButton();
        suppliers_btn = new javax.swing.JButton();
        warranty_btn = new javax.swing.JButton();
        orders_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(129, 135, 177));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("COMPUTER STORE DBMS");

        category_btn.setBackground(new java.awt.Color(59, 75, 125));
        category_btn.setForeground(new java.awt.Color(255, 255, 255));
        category_btn.setText("CATEGORY");
        category_btn.setMaximumSize(new java.awt.Dimension(89, 40));
        category_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category_btnActionPerformed(evt);
            }
        });

        customer_btn.setBackground(new java.awt.Color(59, 75, 125));
        customer_btn.setForeground(new java.awt.Color(255, 255, 255));
        customer_btn.setText("CUSTOMERS");
        customer_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_btnActionPerformed(evt);
            }
        });

        discount_btn.setBackground(new java.awt.Color(59, 75, 125));
        discount_btn.setForeground(new java.awt.Color(255, 255, 255));
        discount_btn.setText("DISCOUNTS");
        discount_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discount_btnActionPerformed(evt);
            }
        });

        inventory_btn.setBackground(new java.awt.Color(59, 75, 125));
        inventory_btn.setForeground(new java.awt.Color(255, 255, 255));
        inventory_btn.setText("INVENTORY");
        inventory_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventory_btnActionPerformed(evt);
            }
        });

        payment_btn.setBackground(new java.awt.Color(59, 75, 125));
        payment_btn.setForeground(new java.awt.Color(255, 255, 255));
        payment_btn.setText("PAYMENT");
        payment_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payment_btnActionPerformed(evt);
            }
        });

        products_btn.setBackground(new java.awt.Color(59, 75, 125));
        products_btn.setForeground(new java.awt.Color(255, 255, 255));
        products_btn.setText("PRODUCTS");
        products_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                products_btnActionPerformed(evt);
            }
        });

        repairs_btn.setBackground(new java.awt.Color(59, 75, 125));
        repairs_btn.setForeground(new java.awt.Color(255, 255, 255));
        repairs_btn.setText("REPAIRS");
        repairs_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repairs_btnActionPerformed(evt);
            }
        });

        services_btn.setBackground(new java.awt.Color(59, 75, 125));
        services_btn.setForeground(new java.awt.Color(255, 255, 255));
        services_btn.setText("SERVICES");
        services_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                services_btnActionPerformed(evt);
            }
        });

        shipping_btn.setBackground(new java.awt.Color(59, 75, 125));
        shipping_btn.setForeground(new java.awt.Color(255, 255, 255));
        shipping_btn.setText("SHIPPING");
        shipping_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shipping_btnActionPerformed(evt);
            }
        });

        suppliers_btn.setBackground(new java.awt.Color(59, 75, 125));
        suppliers_btn.setForeground(new java.awt.Color(255, 255, 255));
        suppliers_btn.setText("SUPPLIERS");
        suppliers_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliers_btnActionPerformed(evt);
            }
        });

        warranty_btn.setBackground(new java.awt.Color(59, 75, 125));
        warranty_btn.setForeground(new java.awt.Color(255, 255, 255));
        warranty_btn.setText("WARRANTY");
        warranty_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warranty_btnActionPerformed(evt);
            }
        });

        orders_btn.setBackground(new java.awt.Color(59, 75, 125));
        orders_btn.setForeground(new java.awt.Color(255, 255, 255));
        orders_btn.setText("ORDERS");
        orders_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orders_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customer_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(category_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(discount_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inventory_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(payment_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(products_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(services_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(repairs_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shipping_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(warranty_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(orders_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(suppliers_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(category_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inventory_btn)
                    .addComponent(warranty_btn)
                    .addComponent(repairs_btn))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payment_btn)
                    .addComponent(customer_btn)
                    .addComponent(services_btn)
                    .addComponent(orders_btn))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(products_btn)
                    .addComponent(discount_btn)
                    .addComponent(shipping_btn)
                    .addComponent(suppliers_btn))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customer_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_btnActionPerformed
        // TODO add your handling code here:
         new customers().setVisible(true); //visible viewUsers
        this.setVisible(false); //invsible this one
    }//GEN-LAST:event_customer_btnActionPerformed

    private void discount_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discount_btnActionPerformed
        // TODO add your handling code here:
        new discounts().setVisible(true); //visible viewUsers
        this.setVisible(false);
    }//GEN-LAST:event_discount_btnActionPerformed

    private void products_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_products_btnActionPerformed
        // TODO add your handling code here:
           new productCus().setVisible(true); //visible viewUsers
        this.setVisible(false);
    }//GEN-LAST:event_products_btnActionPerformed

    private void repairs_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repairs_btnActionPerformed
        // TODO add your handling code here:
        new repairs().setVisible(true); //visible viewUsers
        this.setVisible(false);
    }//GEN-LAST:event_repairs_btnActionPerformed

    private void warranty_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warranty_btnActionPerformed
        // TODO add your handling code here:
           new warranty().setVisible(true); //visible viewUsers
        this.setVisible(false);
    }//GEN-LAST:event_warranty_btnActionPerformed

    private void orders_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orders_btnActionPerformed
        // TODO add your handling code here:
           new orders().setVisible(true); //visible viewUsers
        this.setVisible(false);
    }//GEN-LAST:event_orders_btnActionPerformed

    private void category_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_btnActionPerformed
        // TODO add your handling code here: 
           new category().setVisible(true); //visible viewUsers
        this.setVisible(false);
    }//GEN-LAST:event_category_btnActionPerformed

    private void inventory_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventory_btnActionPerformed
        // TODO add your handling code here:
           new inventory().setVisible(true); //visible viewUsers
        this.setVisible(false);
    }//GEN-LAST:event_inventory_btnActionPerformed

    private void payment_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payment_btnActionPerformed
        // TODO add your handling code here:
           new payments().setVisible(true); //visible viewUsers
        this.setVisible(false);
    }//GEN-LAST:event_payment_btnActionPerformed

    private void services_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_services_btnActionPerformed
        // TODO add your handling code here:
           new service_page().setVisible(true); //visible viewUsers
        this.setVisible(false);
    }//GEN-LAST:event_services_btnActionPerformed

    private void shipping_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shipping_btnActionPerformed
        // TODO add your handling code here:
           new shipping().setVisible(true); //visible viewUsers
        this.setVisible(false);
    }//GEN-LAST:event_shipping_btnActionPerformed

    private void suppliers_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliers_btnActionPerformed
        // TODO add your handling code here:
           new suppliers().setVisible(true); //visible viewUsers
        this.setVisible(false);
    }//GEN-LAST:event_suppliers_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(begin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(begin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(begin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(begin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new begin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton category_btn;
    private javax.swing.JButton customer_btn;
    private javax.swing.JButton discount_btn;
    private javax.swing.JButton inventory_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton orders_btn;
    private javax.swing.JButton payment_btn;
    private javax.swing.JButton products_btn;
    private javax.swing.JButton repairs_btn;
    private javax.swing.JButton services_btn;
    private javax.swing.JButton shipping_btn;
    private javax.swing.JButton suppliers_btn;
    private javax.swing.JButton warranty_btn;
    // End of variables declaration//GEN-END:variables
}
